# Site
name: "Sunset, Seasalt"
title: "Sunset, Seasalt"
description: "The journeys taken, the stories shared, and the memories etched in time."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'sunsetseasalt'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: sunsetseasalt@gmail.com

# Authors
authors:
  azizul:
    name: Azizul
    display_name: Azizul
    avatar: 'assets/images/avatar-azizul.png'
    email: sunsetseasalt@gmail.com
    web: https://paypal.me/azizulwahid12
    twitter: https://twitter.com/azizulwahid12
    description: "Just another boring guy who enjoys writing. Here to share some parts of my journal that breathe life into my otherwise ordinary days."
  yoda:
    name: Yoda
    display_name: Yoda
    avatar: 'assets/images/avatar-yoda.jpg'
    email: sunsetseasalt@gmail.com
    web: https://paypal.me/azizulwahid12
    twitter: https://twitter.com/azizulwahid12
    description: "An AI to help Azizul keep this blog going when he's just not feeling it..."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
